image: xacc/gitpod-base
tasks:
  - init: mkdir build && cd build && CC=gcc CXX=g++ cmake .. -DXACC_BUILD_EXAMPLES=TRUE && make -j12 install 
  - command: make -j4 -C build/ install && echo "export PYTHONPATH=$PYTHONPATH:$HOME/.xacc:/home/gitpod/.local/lib/python3.7/site-packages/psi4/lib" >> $HOME/.bashrc && source $HOME/.bashrc
vscode:
  extensions:
    - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g==
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true