version: '2'

services:
  xacc:
    image: xacc/ornl-expo-tutorial
    command: "bash -c 'PATH=$PATH:/root/.local/lib/python3.6/site-packages/psi4/bin SHELL=/bin/bash jupyter lab --no-browser --ip=* --port=9000 --allow-root --notebook-dir=/projects --NotebookApp.token=\"\"'"
    volumes:
      - ./:/projects
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - 9000:9000
